const MQTT_TOPIC = "/hvac/intesis"

const CONSTANTS = {
    WMP_DEFAULT_PORT: 3310,
    WMP_RECONNECT_TIMEOUT: 5000,
    WMP_KEEP_ALIVE: 30000,
    WMP_KEEP_ALIVE_OFF : "off",
    WMP_KEEP_ALIVE_PING : "ping",
    WMP_KEEP_ALIVE_ID : "id",
    WMP_KEEP_ALIVE_POLLING : "pooling",
    MQTT_DEFAULT_PORT: 1883,
    USAGE_STRING: 'Usage: $0 [--discover] --mqtt [mqtt url] [--wmp ip address(,ip address,...)] [--retain [true/false]]',
    MQTT_TOPIC : MQTT_TOPIC,
    MQTT_STATE_TOPIC : "stat" + MQTT_TOPIC,
    MQTT_COMMAND_TOPIC : "cmnd" + MQTT_TOPIC,
    MQTT_COMMAND_SETTINGS_SUFFIX : "SETTINGS",
    MQTT_COMMAND_LIMITS_SUFFIX : "LIMITS",
    MQTT_COMMAND_LIMITS_TOPIC : "limits",
    MQTT_COMMAND_ID_SUFFIX : "ID",
    MQTT_COMMAND_INFO_SUFFIX : "INFO",
    MQTT_DEFAULT_KEEPALIVE : 60,
    MQTT_INTESIS_AVAILABILITY_TOPIC_SUFFIX : "status",
    MQTT_INTESIS_AVAILABILITY_PAYLOAD_ONLINE : "online",
    MQTT_INTESIS_AVAILABILITY_PAYLOAD_OFFLINE : "offline",
    MQTT_INTESIS_STANDBY_MODE : "STANDBYMODE",
    DISCOVER_WAIT : 10,
    INTESIS_BOX : "box",
    INTESIS_GATEWAY : "gateway",
    INTESIS_DISABLED : "DISABLED",
    INTESIS_READY_TIMEOUT : 10000,
    INTESIS_READY_DELAY : 1000,
}

module.exports = CONSTANTS;
